defaults: &defaults
  adapter: sqlite3
  database: db/backstage_<%= Rails.env %>.sqlite3

test:
  <<: *defaults

development:
  <<: *defaults

wip:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults