development:
  adapter: postgresql
  database: backstage2_development

test:
  adapter: postgresql
  database: backstage2_test

wip:
  adapter: postgresql
  database: backstage2_wip

staging:
  adapter: postgresql
  database: backstage2_staging

production:
  adapter: postgresql
  database: backstage2_production
