defaults: &defaults
  adapter: postgresql
  database: backstage2_<%= Rails.env %>

test:
  <<: *defaults

development:
  <<: *defaults

wip:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
